name: customerfeedbackios
description: CustomerFeedback project for Android and IOS
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  i2iutils:
    path: 'package/i2iutils'

  cupertino_icons: ^1.0.2
  flutter_easyloading: 3.0.5
#  toast: 0.3.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
#  flutter_platform_widgets: ^2.0.0
  video_player: ^2.4.7
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  device_info: ^2.0.3
  sqflite: ^2.0.3+1
  dio: 4.0.6
  awesome_snackbar_content: ^0.0.8
  flutter_otp_text_field: ^1.1.0+2
  percent_indicator: ^4.0.1
  signature: ^5.2.1
  google_fonts:
  page_transition: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

  flutter_lints: ^2.0.0

flutter_icons: #flutter pub run flutter_launcher_icons
  android: true
  ios: true
  image_path: "assets/images/appstore.png"
  background_color: "#FFFFFF"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/